- name: "status --- :grey_question:"
  color: "FBCA04"
  description: "further information is currently being requested"
- name: "status --- good first action"
  color: "0E8A16"
  description: "good for newcomers"
- name: "status --- help wanted :heart:"
  color: "0E8A16"
  description: "we would love your help"
- name: "status --- high priority"
  color: "0E8A16"
- name: "status --- low priority"
  color: "FBCA04"
- name: "status --- needs testing"
  color: "FBCA04"
  description: "code is in place but testing is needed"
- name: "status --- on hold"
  color: "FBCA04"
  description: "started but put in a holding pattern for now"
- name: "status --- wip"
  color: "0E8A16"
  description: "work in progress"
- name: "topic --- ghaction"
  color: "eeeeee"
  description: "GitHub action"
- name: "type --- :bug:"
  color: "fc2929"
  description: "an unexpected problem or unintended behavior"
- name: "type --- documentation"
  color: "84b6eb"
  description: "requires changes to the docs"
- name: "type --- feature"
  color: "84b6eb"
  description: "feature requests and enhancement"
- name: "type --- tip"
  color: "84b6eb"
- name: "type --- upkeep"
  color: "84b6eb"
  description: "general package maintenance work that makes future development easier"
